Repository tobspr/shapez.io, pull requests merged in 2020-07, with the labels that each got.

#372 Fixed an issue that caused an error when pressing the tab key
  src/js/game/hud/parts/base_toolbar.js
Labels: changes-required

#386 Center zoom on mouse
  src/js/game/camera.js
Labels: changes-required

#383 Confirm cutting if not enough shapes to rebuild blueprint back
  src/js/game/hud/parts/mass_selector.js
  translations/base-en.yaml
  translations/base-ja.yaml
Labels: changes-required

#347 Improved debug info (position and version)
  src/css/ingame_hud/debug_info.scss
  src/js/game/hud/parts/debug_info.js
Labels: changes-required

#367 Initial planner direction based on cursor movement
  src/js/game/hud/parts/building_placer_logic.js
Labels: looks-good-needs-testing

#397 Changed "Delete marker" to "Show rename (or delete) marker dialog"
  src/css/ingame_hud/waypoints.scss
  src/js/core/modal_dialog_elements.js
  src/js/game/hud/parts/waypoints.js
  translations/base-en.yaml
  translations/base-ja.yaml
Labels: changes-required

#423 Update base-no.yaml
  translations/base-no.yaml
Labels: changes-required

#439 Updated french translation
  translations/base-fr.yaml
Labels: changes-required

#442 Pt br fixes
  translations/base-pt-BR.yaml
Labels: changes-required

#443 French translation update
  translations/base-fr.yaml
Labels: changes-required

#482 Major ui changes
  src/css/common.scss
  src/css/states/about.scss
  src/css/states/changelog.scss
  src/css/states/settings.scss
  src/css/textual_game_state.scss
  src/js/changelog.js
  src/js/profile/application_settings.js
  src/js/states/about.js
  src/js/states/settings.js
  translations/README.md
  translations/base-ar.yaml
  translations/base-cat.yaml
  translations/base-cz.yaml
  translations/base-da.yaml
  translations/base-de.yaml
  translations/base-el.yaml
  translations/base-en.yaml
  translations/base-es.yaml
  translations/base-fi.yaml
  translations/base-fr.yaml
  translations/base-hr.yaml
  translations/base-hu.yaml
  translations/base-ind.yaml
  translations/base-it.yaml
  translations/base-ja.yaml
  translations/base-kor.yaml
  translations/base-lt.yaml
  translations/base-nl.yaml
  translations/base-no.yaml
  translations/base-pl.yaml
  translations/base-pt-BR.yaml
  translations/base-pt-PT.yaml
  translations/base-ro.yaml
  translations/base-ru.yaml
  translations/base-sl.yaml
  translations/base-sr.yaml
  translations/base-sv.yaml
  translations/base-tr.yaml
  translations/base-uk.yaml
  translations/base-zh-CN.yaml
  translations/base-zh-TW.yaml
Labels: looks-good-needs-testing

#138 Redo stacking algorithm
  src/js/game/shape_definition.js
Labels: looks-good-but-needs-thought

#352 Fix layer handling in cutter
  src/js/game/shape_definition.js
Labels: looks-good-but-needs-thought

#418 [WIP] Update base-uk.yaml
  translations/base-uk.yaml
Labels: on hold

#486 [Perf] Avoid iterating over keys to generate assert message
  src/js/core/sprites.js
Labels: changes-required
