Repository tobspr/shapez.io, pull requests merged in 2020-12, with the labels that each got.

#703 Added layersupport to waypoints!!
  src/js/game/hud/parts/waypoints.js
  src/js/savegame/savegame.js
  src/js/savegame/savegame_interface_registry.js
  src/js/savegame/schemas/1007.js
  src/js/savegame/schemas/1007.json
Labels: looks-good-needs-testing

#830 Format all upgrade tiers as Roman numerals
  src/js/core/utils.js
Labels: on hold

#887 Update base-nl.yaml
  translations/base-nl.yaml
Labels: changes-required

#950 Fixed french translation
  translations/base-fr.yaml
Labels: changes-required
