Repository tobspr/shapez.io, pull requests merged in 2021-08, with the labels that each got.

#1191 Update base-fr.yaml
  translations/base-fr.yaml
Labels: changes-required

#1251 Added shape tooltip - final version
  src/js/game/components/item_ejector.js
  src/js/game/hud/hud.js
  src/js/game/hud/parts/shape_tooltip.js
  src/js/game/key_action_mapper.js
  src/js/game/modes/puzzle.js
  src/js/game/systems/item_processor.js
  translations/base-en.yaml
Labels: planned

#1033 Fix selected building being deselected at level up
  src/js/game/hud/parts/building_placer_logic.js
Labels: looks-good-needs-testing

#1247 Aggregate map chunks in overlay.
  src/js/core/buffer_maintainer.js
  src/js/core/config.js
  src/js/game/map.js
  src/js/game/map_chunk_aggregate.js
  src/js/game/map_chunk_view.js
  src/js/game/map_view.js
Labels: planned
